### ISSUE TITLE
feature request: 支持URL Scheme/x-callback-url

### ISSUE THREAD

**Issue by iyee** [wujichao/hipda_ios_client_v3#14]
刚在iTunes AppStore上买了，体验不错，希望能支持URL Scheme调用，这样搭配Launch Center Pro和Drafts会更方便。

**Comment by wujichao** [comment]
hipda://

**Comment by iyee** [comment]
@wujichao 能不能支持传参跳入对应版面？比如我想直接看eink板块（forumid=59）而不是去d版。
