### ISSUE TITLE
Storage Usage 很大 （实现HPURLCache，替换SDURLCache）

### ISSUE THREAD

**Issue by nkcfan** [wujichao/hipda_ios_client_v3#17]
在我的iphone上，清除了客户端的缓存，Setting > General > Usage > Manage Storage 里面的占用量还有237 MB，为什么会这么大呢？

**Comment by wujichao** [comment]
https://github.com/wujichao/hipda_ios_client_v3/commit/34a05f898a18e959f9f511cdb27809277d3649d1
